name: Notifica√ß√£o de Resultado de Testes

on:
  workflow_run:
    workflows:
      - "Testes Regressivos API Random User"
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Definir nome do workflow
        run: echo "NOME_DO_WORKFLOW=Testes Regressivos API Random User" >> $GITHUB_ENV

      - name: Enviar notifica√ß√£o pelo Telegram - Sucesso
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Workflow: ${{ env.NOME_DO_WORKFLOW }} üíª
            Evento: ${{ github.event.workflow_run.event }}
            Status: A esteira foi executada com sucesso ‚úÖ
            Reposit√≥rio: https://github.com/Srjordao/ApiRandomUser

      - name: Enviar notifica√ß√£o pelo Telegram - Falha
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Workflow: ${{ env.NOME_DO_WORKFLOW }} üíª
            Evento: ${{ github.event.workflow_run.event }}
            Status: A esteira falhou ‚ùå
            Reposit√≥rio: https://github.com/Srjordao/ApiRandomUser
